org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=accurateblockplacement
mod_name=Accurate Block Placement
mod_license=MIT
mod_version=1.3.0
mod_group_id=net.clayborn.accurateblockplacement
mod_authors=Clayborn, Flourick, KadTheHunter, schwar
mod_description=Build at super speed with your bare hands! Hold right-click to place blocks rapidly without double-placing on the same spot.
